### ISSUE TITLE
shuts down if no internet

### ISSUE THREAD

**Issue by yasushisakai** [ChristopherSweeney/Bike-Bump#1]
without cellular and wifi connection, the app shuts down.
it should .... (I bet 1 is easier?)

1. skip the fetching LatLng or uploading the soundClip
2. wait until it has wifi?

**Comment by ChristopherSweeney** [comment]
I have not been able to reproduce this problem. Does the app crash?

**Comment by yasushisakai** [comment]
yup it crashes

**Comment by ChristopherSweeney** [comment]
are you on the most recent build? my app works fine if i set it to airplane
mode.

**Comment by ChristopherSweeney** [comment]
I figured out the problem, the new UI caused a bug into the transition
between different views. should be resolved now.

**Comment by yasushisakai** [comment]
great! thanks
